package org.agty.sql.session;

import org.agty.sql.AgtySQL;
import org.agty.sql.config.AgtySqlConfig;
import org.agty.sql.config.AgtySqlConfigInit;
import org.agty.sql.dialect.DialectDriverRegistry;
import org.agty.sql.exceptions.AgtySqlException;
import org.agty.sql.support.DebugMessages;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Owns connection lifecycle for an AgtySQL session.
 */
public class AgtySqlConnector {

    private final int defaultStatementRows = 100;
    private int stmtRows;
    private AgtySqlConfig config;
    private Connection connection;
    private int fetchSize;
    private boolean noClosable;

    public AgtySqlConnector() {
        configInit("default");
    }

    public AgtySqlConnector(String server) {
        configInit(server);
    }

    public AgtySqlConnector(String server, String path) {
        configInit(server, path);
    }

    public AgtySqlConnector(AgtySqlConfig agtySqlConfig) {
        configInit(agtySqlConfig);
    }

    private void configInit(String server) {
        if (config == null) {
            config = new AgtySqlConfigInit(server).getConfig();
        }
    }

    private void configInit(String server, String path) {
        if (config == null) {
            config = new AgtySqlConfigInit(server, path).getConfig();
        }
    }

    private void configInit(AgtySqlConfig agtySqlConfig) {
        if (config == null) {
            config = AgtySqlConfig.getClone(agtySqlConfig);
        }
    }

    public void setNoClosable(boolean noClosable) {
        this.noClosable = noClosable;
    }

    public boolean isNoClosable() {
        return noClosable;
    }

    public AgtySqlConfig getConfig() {
        return config;
    }

    public boolean isCheckConfig() {
        String driver = getConfig().getDriver();

        if ("sqlite".equalsIgnoreCase(driver) || "h2".equalsIgnoreCase(driver)) {
            return getConfig().isDatabase() && !getConfig().getDatabase().isEmpty();
        }

        return !getConfig().getUser().isEmpty()
                && !getConfig().getPassword().isEmpty()
                && !getConfig().getServer().isEmpty()
                && getConfig().getPort() != 0;
    }

    private String getDriverName() {
        return DialectDriverRegistry.getDriverName(getConfig().getDriver());
    }

    public Connection getConnection() throws SQLException {
        if (connection == null) {
            connection = createConnection();
        }
        return connection;
    }

    public void checkAndReconnectConnection() throws SQLException {
        if (connection == null) {
            return;
        }

        String driver = getConfig().getDriver();
        if ("sqlite".equalsIgnoreCase(driver) || "h2".equalsIgnoreCase(driver)) {
            if (connection.isClosed()) {
                connection = createConnection();
            }
            return;
        }

        if (!connection.isValid(100)) {
            connection.close();
            connection = createConnection();
        }
    }

    private Connection createConnection() throws SQLException {
        debugMessage("AgtySqlConnector.createConnect()", "v." + AgtySQL.VERSION + "; server: " + getConfig().getDriver());

        if (!isCheckConfig()) {
            throw new AgtySqlException("AgtySqlConnector.createConnect()", "Config: One of default parameters is null");
        }

        return new AgtySqlConnection(getConfig(), getDriverName()).getConnection();
    }

    public Statement getStatement() throws SQLException {
        checkAndReconnectConnection();
        return new AgtySqlStatement(getConnection(), getConfig(), getStmtRows(), getFetchSize()).getStatement();
    }

    public void setFetchSize(int fetchSize) {
        this.fetchSize = fetchSize;
    }

    public int getFetchSize() {
        return fetchSize;
    }

    public PreparedStatement prepareStatement(String query) throws SQLException {
        checkAndReconnectConnection();
        return getConnection().prepareStatement(query);
    }

    public PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
        checkAndReconnectConnection();
        return getConnection().prepareStatement(query, autoGeneratedKeys);
    }

    public Statement createBatchStatement() throws SQLException {
        checkAndReconnectConnection();
        return new AgtySqlStatement(getConnection(), getConfig(), getStmtRows(), getFetchSize()).getStatement();
    }

    public boolean isAutoCommit() throws SQLException {
        return getConnection().getAutoCommit();
    }

    public void setAutoCommit(Boolean commit) {
        try {
            getConnection().setAutoCommit(commit);
        } catch (SQLException e) {
            throw new AgtySqlException("AgtySqlConnector.setAutoCommit()", e.getMessage());
        }
    }

    public void commit() throws SQLException {
        getConnection().commit();
    }

    public void rollback() throws SQLException {
        getConnection().rollback();
    }

    public void close() throws SQLException {
        if (isNoClosable()) {
            return;
        }

        if (connection != null) {
            getConnection().close();
        }

        connection = null;

        debugMessage("AgtySqlConnector.close()", getConfig().getServer() + "/" + getConfig().getDriver() + " -> Connect closed");
    }

    public int getStmtRows() {
        if (stmtRows > 0) {
            return stmtRows;
        }
        if (getConfig().getStmtRows() > 0) {
            return getConfig().getStmtRows();
        }
        return defaultStatementRows;
    }

    public void setStmtRows(int stmtRows) {
        this.stmtRows = stmtRows;
    }

    private void debugMessage(String type, String message) {
        if (getConfig().isDebug()) {
            DebugMessages.print(type, message);
        }
    }
}
