package org.agty.sql.support;

import org.agty.sql.driver.DialectCapabilities;
import org.agty.sql.driver.LastInsertIdStrategy;
import org.agty.sql.driver.UpdateAndGetStrategy;
import org.agty.sql.driver.WriteReturnStrategy;

import java.util.stream.Stream;

public final class TestDatabaseProfiles {

    private TestDatabaseProfiles() {
    }

    public static Stream<TestDatabaseProfile> sqlProfiles() {
        return Stream.of(
                new TestDatabaseProfile(
                        "mysql",
                        "{integration_smoke_mysql}",
                        """
                        CREATE TABLE {table} (
                            id BIGINT PRIMARY KEY,
                            string VARCHAR(255),
                            integers INT,
                            bool BOOLEAN
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                        """,
                        """
                        CREATE TABLE {table} (
                            id BIGINT PRIMARY KEY AUTO_INCREMENT,
                            string VARCHAR(255)
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                        """,
                        DialectCapabilities.of(
                                false,
                                false,
                                LastInsertIdStrategy.CONNECTION_FUNCTION,
                                WriteReturnStrategy.FOLLOW_UP_FETCH,
                                UpdateAndGetStrategy.FOLLOW_UP_FETCH_BY_WHERE
                        )
                ),
                new TestDatabaseProfile(
                        "mariadb",
                        "{integration_smoke_mariadb}",
                        """
                        CREATE TABLE {table} (
                            id BIGINT PRIMARY KEY,
                            string VARCHAR(255),
                            integers INT,
                            bool BOOLEAN
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                        """,
                        """
                        CREATE TABLE {table} (
                            id BIGINT PRIMARY KEY AUTO_INCREMENT,
                            string VARCHAR(255)
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                        """,
                        DialectCapabilities.of(
                                false,
                                false,
                                LastInsertIdStrategy.CONNECTION_FUNCTION,
                                WriteReturnStrategy.FOLLOW_UP_FETCH,
                                UpdateAndGetStrategy.FOLLOW_UP_FETCH_BY_WHERE
                        )
                ),
                new TestDatabaseProfile(
                        "pgsql",
                        "{integration_smoke_pgsql}",
                        """
                        CREATE TABLE {table} (
                            id BIGINT PRIMARY KEY,
                            string VARCHAR(255),
                            integers INT,
                            bool BOOLEAN
                        )
                        """,
                        """
                        CREATE TABLE {table} (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            string VARCHAR(255)
                        )
                        """,
                        DialectCapabilities.of(
                                false,
                                true,
                                LastInsertIdStrategy.SEQUENCE_FUNCTION,
                                WriteReturnStrategy.NATIVE_RETURNING,
                                UpdateAndGetStrategy.NATIVE_RETURNING
                        )
                ),
                new TestDatabaseProfile(
                        "mssql",
                        "{integration_smoke_mssql}",
                        """
                        CREATE TABLE {table} (
                            id BIGINT PRIMARY KEY,
                            string VARCHAR(255),
                            integers INT,
                            bool BIT
                        )
                        """,
                        """
                        CREATE TABLE {table} (
                            id BIGINT IDENTITY(1,1) PRIMARY KEY,
                            string VARCHAR(255)
                        )
                        """,
                        DialectCapabilities.of(
                                false,
                                true,
                                LastInsertIdStrategy.CONNECTION_FUNCTION,
                                WriteReturnStrategy.NATIVE_RETURNING,
                                UpdateAndGetStrategy.NATIVE_RETURNING
                        )
                ),
                new TestDatabaseProfile(
                        "sqlite",
                        "{integration_smoke_sqlite}",
                        """
                        CREATE TABLE {table} (
                            id INTEGER PRIMARY KEY,
                            string VARCHAR(255),
                            integers INT,
                            bool BOOLEAN
                        )
                        """,
                        """
                        CREATE TABLE {table} (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                            string VARCHAR(255)
                        )
                        """,
                        DialectCapabilities.of(
                                true,
                                false,
                                LastInsertIdStrategy.CONNECTION_FUNCTION,
                                WriteReturnStrategy.FOLLOW_UP_FETCH,
                                UpdateAndGetStrategy.FOLLOW_UP_FETCH_BY_WHERE
                        )
                ),
                new TestDatabaseProfile(
                        "h2",
                        "{integration_smoke_h2}",
                        """
                        CREATE TABLE {table} (
                            id BIGINT PRIMARY KEY,
                            string VARCHAR(255),
                            integers INT,
                            bool BOOLEAN
                        )
                        """,
                        """
                        CREATE TABLE {table} (
                            id BIGINT AUTO_INCREMENT PRIMARY KEY,
                            string VARCHAR(255)
                        )
                        """,
                        DialectCapabilities.of(
                                true,
                                true,
                                LastInsertIdStrategy.FETCH_LAST_ROW_UNSAFE,
                                WriteReturnStrategy.FOLLOW_UP_FETCH,
                                UpdateAndGetStrategy.FOLLOW_UP_FETCH_BY_WHERE
                        )
                )
        );
    }

    public static Stream<TestDatabaseProfile> profilesSupportingLastInsertId() {
        return sqlProfiles()
                .filter(profile -> profile.capabilities().supportsLastInsertId());
    }

    public static Stream<TestDatabaseProfile> profilesSupportingInsertAndGetReturning() {
        return sqlProfiles()
                .filter(profile -> profile.capabilities().supportsInsertAndGetReturning());
    }

    public static Stream<TestDatabaseProfile> profilesSupportingUpdateAndGet() {
        return sqlProfiles()
                .filter(profile -> profile.capabilities().supportsUpdateAndGet());
    }
}
