package org.agty.sql;

import org.agty.sql.config.AgtySqlConfig;
import org.agty.sql.connect.AgtySqlConnector;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Internal bridge used to isolate session/connection lifecycle from the facade.
 */
public final class AgtySqlSessionSupport {

    private final AgtySqlConnector connector;

    AgtySqlSessionSupport(AgtySqlConnector connector) {
        this.connector = connector;
    }

    /**
     * Returns the config.
     * @return operation result
     */
    public AgtySqlConfig getConfig() {
        return connector.getConfig();
    }

    /**
     * Sets the stmt rows.
     * @param stmtRows parameter value
     */
    public void setStmtRows(int stmtRows) {
        connector.setStmtRows(stmtRows);
    }

    /**
     * Sets the fetch size.
     * @param fetchSize parameter value
     */
    public void setFetchSize(int fetchSize) {
        connector.setFetchSize(fetchSize);
    }

    /**
     * Returns the fetch size.
     * @return operation result
     */
    public int getFetchSize() {
        return connector.getFetchSize();
    }

    /**
     * Returns the connection.
     * @return operation result
     * @throws SQLException if the operation cannot be completed
     */
    public Connection getConnection() throws SQLException {
        return connector.getConnection();
    }

    /**
     * Returns the statement.
     * @return operation result
     * @throws SQLException if the operation cannot be completed
     */
    public Statement getStatement() throws SQLException {
        return connector.getStatement();
    }

    /**
     * Performs the prepare statement operation.
     * @param query parameter value
     * @return operation result
     * @throws SQLException if the operation cannot be completed
     */
    public PreparedStatement prepareStatement(String query) throws SQLException {
        return connector.prepareStatement(query);
    }

    /**
     * Performs the prepare statement operation.
     * @param query parameter value
     * @param autoGeneratedKeys parameter value
     * @return operation result
     * @throws SQLException if the operation cannot be completed
     */
    public PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
        return connector.prepareStatement(query, autoGeneratedKeys);
    }

    /**
     * Performs the create batch statement operation.
     * @return operation result
     * @throws SQLException if the operation cannot be completed
     */
    public Statement createBatchStatement() throws SQLException {
        return connector.createBatchStatement();
    }

    /**
     * Returns whether auto commit.
     * @return operation result
     * @throws SQLException if the operation cannot be completed
     */
    public boolean isAutoCommit() throws SQLException {
        return connector.isAutoCommit();
    }

    /**
     * Performs the commit operation.
     * @throws SQLException if the operation cannot be completed
     */
    public void commit() throws SQLException {
        connector.commit();
    }

    /**
     * Sets the auto commit.
     * @param autocommit parameter value
     * @throws SQLException if the operation cannot be completed
     */
    public void setAutoCommit(boolean autocommit) throws SQLException {
        connector.getConnection().setAutoCommit(autocommit);
    }

    /**
     * Performs the rollback operation.
     * @throws SQLException if the operation cannot be completed
     */
    public void rollback() throws SQLException {
        connector.rollback();
    }

    /**
     * Performs the close operation.
     * @throws SQLException if the operation cannot be completed
     */
    public void close() throws SQLException {
        connector.close();
    }
}
