package org.agty.sql;

import org.agty.sql.config.AgtySqlConfig;
import org.agty.sql.data.Arguments;
import org.agty.sql.driver.DialectCapabilities;
import org.agty.sql.interfaces.Sql;
import org.agty.sql.interfaces.SqlRow;
import org.agty.sql.support.PreparedStatementSupport;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 * Internal bridge used by operation classes moved out of the root package.
 */
public final class AgtySqlOperationSupport {

    private final AgtySQL agtySQL;

    AgtySqlOperationSupport(AgtySQL agtySQL) {
        this.agtySQL = agtySQL;
    }

    public AgtySqlConfig getConfig() {
        return agtySQL.getConfig();
    }

    public AgtySQL getAgtySQL() {
        return agtySQL;
    }

    public boolean hasErrors() {
        return agtySQL.hasErrors();
    }

    public boolean hasQuery(Arguments arguments) {
        return agtySQL.hasQueryInternal(arguments);
    }

    public boolean hasQuery(String query) {
        return agtySQL.hasQueryInternal(query);
    }

    public Sql getDriverSqlObject() {
        return agtySQL.getDriverSqlObjectInternal();
    }

    public SqlRow getFetchRow(ResultSet resultSet, Arguments arguments) throws SQLException {
        return agtySQL.getFetchRowInternal(resultSet, arguments);
    }

    public ResultSet executeQuery(String query, boolean noRebuildQuery) {
        return agtySQL.executeQueryInternal(query, noRebuildQuery);
    }

    public AgtySqlCursor createManagedCursor(ResultSet resultSet, Arguments arguments) {
        return agtySQL.createManagedCursor(resultSet, arguments);
    }

    public boolean execute(String query, boolean noRebuildQuery) {
        return agtySQL.execute(query, noRebuildQuery);
    }

    public Long executeUpdate(String query) {
        return agtySQL.executeUpdate(query);
    }

    public ResultSet executePreparedQuery(
            String query,
            List<?> parameters,
            boolean noRebuildQuery
    ) {
        PreparedStatement statement = agtySQL.prepareStatement(query, noRebuildQuery);
        if (statement == null) {
            return null;
        }

        try {
            PreparedStatementSupport.bind(statement, parameters);
            return statement.executeQuery();
        } catch (SQLException e) {
            closeAfterFailure(statement, e);
            agtySQL.throwErrorInternal("AgtySQL.executePreparedQuery()", e);
            return null;
        }
    }

    public long executePreparedUpdate(
            String query,
            List<?> parameters,
            boolean noRebuildQuery
    ) {
        try (PreparedStatement statement = agtySQL.prepareStatement(query, noRebuildQuery)) {
            if (statement == null) {
                return 0L;
            }

            PreparedStatementSupport.bind(statement, parameters);
            return getDriverSqlObject().isSupportLargeUpdate()
                    ? statement.executeLargeUpdate()
                    : statement.executeUpdate();
        } catch (SQLException e) {
            agtySQL.throwErrorInternal("AgtySQL.executePreparedUpdate()", e);
            return 0L;
        }
    }

    public Long lastInsertId(Arguments arguments) {
        return agtySQL.lastInsertIdInternal(arguments);
    }

    public PreparedStatement prepareStatement(String query, int autoGeneratedKeys, boolean noRebuildQuery) {
        return agtySQL.prepareStatement(query, autoGeneratedKeys, noRebuildQuery);
    }

    public PreparedStatement prepareStatement(String query, boolean noRebuildQuery) {
        return agtySQL.prepareStatement(query, noRebuildQuery);
    }

    public void bind(PreparedStatement statement, List<?> parameters) throws SQLException {
        PreparedStatementSupport.bind(statement, parameters);
    }

    public String rebuildTable(String table) {
        return agtySQL.rebuildTable(table);
    }

    public SqlRow fetch(Arguments arguments) {
        return agtySQL.fetch(arguments);
    }

    public SqlRow fetch(String query) {
        return agtySQL.fetch(query);
    }

    public void throwError(String type, String message) {
        agtySQL.throwErrorInternal(type, message);
    }

    public void throwError(String type, Throwable cause) {
        agtySQL.throwErrorInternal(type, cause);
    }

    public void debugMessage(String type, String message) {
        agtySQL.debugMessageInternal(type, message);
    }

    public void debugMessageEnterInMethod(String method) {
        agtySQL.debugMessageEnterInMethodInternal(method);
    }

    public ResultSet getListResultSet(int index) {
        return agtySQL.getListResultSetInternal(index);
    }

    public void setListResultSet(ResultSet resultSet, int index) {
        agtySQL.setListResultSetInternal(resultSet, index);
    }

    public boolean hasListResultSet(int index) {
        return agtySQL.hasListResultSetInternal(index);
    }

    public void clearListResultSet(int index) {
        agtySQL.clearListResultSetInternal(index);
    }

    public DialectCapabilities getDialectCapabilities() {
        return agtySQL.getDialectCapabilities();
    }

    public SqlRow getGeneratedKeys(PreparedStatement preparedStatement, boolean convertValueToString) {
        return agtySQL.getGeneratedKeys(preparedStatement, convertValueToString);
    }

    private void closeAfterFailure(PreparedStatement statement, SQLException failure) {
        try {
            statement.close();
        } catch (SQLException closeException) {
            failure.addSuppressed(closeException);
        }
    }
}
