package org.agty.sql;

import org.agty.sql.config.AgtySqlConfig;
import org.agty.sql.data.Arguments;
import org.agty.sql.driver.DialectCapabilities;
import org.agty.sql.interfaces.Sql;
import org.agty.sql.interfaces.SqlRow;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Internal bridge used by operation classes moved out of the root package.
 */
public final class AgtySqlOperationSupport {

    private final AgtySQL agtySQL;

    AgtySqlOperationSupport(AgtySQL agtySQL) {
        this.agtySQL = agtySQL;
    }

    public AgtySqlConfig getConfig() {
        return agtySQL.getConfig();
    }

    public AgtySQL getAgtySQL() {
        return agtySQL;
    }

    public boolean hasErrors() {
        return agtySQL.hasErrors();
    }

    public boolean hasQuery(Arguments arguments) {
        return agtySQL.hasQueryInternal(arguments);
    }

    public boolean hasQuery(String query) {
        return agtySQL.hasQueryInternal(query);
    }

    public Sql getDriverSqlObject() {
        return agtySQL.getDriverSqlObjectInternal();
    }

    public SqlRow getFetchRow(ResultSet resultSet, Arguments arguments) throws SQLException {
        return agtySQL.getFetchRowInternal(resultSet, arguments);
    }

    public ResultSet executeQuery(String query, boolean noRebuildQuery) {
        return agtySQL.executeQueryInternal(query, noRebuildQuery);
    }

    public boolean execute(String query, boolean noRebuildQuery) {
        return agtySQL.execute(query, noRebuildQuery);
    }

    public Long executeUpdate(String query) {
        return agtySQL.executeUpdate(query);
    }

    public Long lastInsertId(Arguments arguments) {
        return agtySQL.lastInsertIdInternal(arguments);
    }

    public PreparedStatement prepareStatement(String query, int autoGeneratedKeys, boolean noRebuildQuery) {
        return agtySQL.prepareStatement(query, autoGeneratedKeys, noRebuildQuery);
    }

    public String rebuildTable(String table) {
        return agtySQL.rebuildTable(table);
    }

    public SqlRow fetch(Arguments arguments) {
        return agtySQL.fetch(arguments);
    }

    public SqlRow fetch(String query) {
        return agtySQL.fetch(query);
    }

    public void throwError(String type, String message) {
        agtySQL.throwErrorInternal(type, message);
    }

    public void debugMessage(String type, String message) {
        agtySQL.debugMessageInternal(type, message);
    }

    public void debugMessageEnterInMethod(String method) {
        agtySQL.debugMessageEnterInMethodInternal(method);
    }

    public ResultSet getListResultSet(int index) {
        return agtySQL.getListResultSetInternal(index);
    }

    public void setListResultSet(ResultSet resultSet, int index) {
        agtySQL.setListResultSetInternal(resultSet, index);
    }

    public boolean hasListResultSet(int index) {
        return agtySQL.hasListResultSetInternal(index);
    }

    public void clearListResultSet(int index) {
        agtySQL.clearListResultSetInternal(index);
    }

    public DialectCapabilities getDialectCapabilities() {
        return agtySQL.getDialectCapabilities();
    }

    public SqlRow getGeneratedKeys(PreparedStatement preparedStatement, boolean convertValueToString) {
        return agtySQL.getGeneratedKeys(preparedStatement, convertValueToString);
    }
}
