package org.agty.sql;

import org.agty.sql.config.AgtySqlConfig;
import org.agty.sql.connect.AgtySqlConnector;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Internal bridge used to isolate session/connection lifecycle from the facade.
 */
public final class AgtySqlSessionSupport {

    private final AgtySqlConnector connector;

    AgtySqlSessionSupport(AgtySqlConnector connector) {
        this.connector = connector;
    }

    public AgtySqlConfig getConfig() {
        return connector.getConfig();
    }

    public void setStmtRows(int stmtRows) {
        connector.setStmtRows(stmtRows);
    }

    public void setFetchSize(int fetchSize) {
        connector.setFetchSize(fetchSize);
    }

    public int getFetchSize() {
        return connector.getFetchSize();
    }

    public Connection getConnection() throws SQLException {
        return connector.getConnection();
    }

    public Statement getStatement() throws SQLException {
        return connector.getStatement();
    }

    public PreparedStatement prepareStatement(String query) throws SQLException {
        return connector.prepareStatement(query);
    }

    public PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
        return connector.prepareStatement(query, autoGeneratedKeys);
    }

    public Statement createBatchStatement() throws SQLException {
        return connector.createBatchStatement();
    }

    public boolean isAutoCommit() throws SQLException {
        return connector.isAutoCommit();
    }

    public void commit() throws SQLException {
        connector.commit();
    }

    public void setAutoCommit(boolean autocommit) throws SQLException {
        connector.getConnection().setAutoCommit(autocommit);
    }

    public void rollback() throws SQLException {
        connector.rollback();
    }

    public void close() throws SQLException {
        connector.close();
    }
}
